project:
  type: website

website:
  title: "MKE Property Networks"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - top15.qmd
      - evictions.qmd
      - code-enforcement.qmd
      - census-comparison.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



